WIFI_CONFIGURATION = { }
WIFI_CONFIGURATION.ssid = nil
WIFI_CONFIGURATION.password = nil

MQTT_CONFIGURATION = { }
MQTT_CONFIGURATION.host = nil
MQTT_CONFIGURATION.port = 1883
MQTT_CONFIGURATION.isSecure = false
